version: "3.7"

services:
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - cache
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  cache:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  queue:
    restart: always
    build: ./web
    command: celery --app config worker --loglevel=INFO --logfile=logs/celery.log
    volumes:
      - ./web:/home/app/web
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - cache
volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
