version: "3.7"

services:
  cache:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  nginx:
    restart: always
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - /etc/letsencrypt:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    restart: always
    image: "${WEB_IMAGE}"
    command: /home/app/web/.venv/bin/gunicorn config.wsgi:application --bind 0.0.0.0:8000 --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - cache
  queue-worker:
    restart: always
    image: "${WEB_IMAGE}"
    command: /home/app/web/.venv/bin/celery -A config worker --loglevel INFO --logfile logs/celery-worker.log
    env_file:
      - .env
    depends_on:
      - cache
  queue-scheduler:
    restart: always
    image: "${WEB_IMAGE}"
    command: /home/app/web/.venv/bin/celery -A config beat --loglevel INFO --logfile logs/celery-beat.log --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - cache
  queue-dashboard:
    restart: always
    image: "${WEB_IMAGE}"
    command: /home/app/web/.venv/bin/celery -A config worker --loglevel INFO --logfile logs/celery-worker.log
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - cache
volumes:
  redis_data:
  static_volume:
  media_volume:
