version: "3.7"

services:
  web:
    restart: always
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - cache
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  cache:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  queue:
    restart: always
    build: ./web
    command: celery --app config worker --loglevel=INFO --logfile=logs/celery.log
    volumes:
      - ./web:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - cache

volumes:
  postgres_data:
  redis_data:
