# Generated by Django 3.2 on 2021-04-29 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunitmeasurement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalteam',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsettings',
            name='default_unit_volume',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalsettings',
            name='default_unit_weight',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalsettings',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalresource',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproductconversion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproductconversion',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='historicalproductcharacteristics',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproductcharacteristics',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmaterialconversion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmaterialconversion',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='historicalmaterialcharacteristics',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmaterialcharacteristics',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitemconversion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitemconversion',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='historicalitemcharacteristics',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitemcharacteristics',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsyield',
            name='bill_of_materials',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsyield',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsyield',
            name='unit_each',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsyield',
            name='unit_volume',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsyield',
            name='unit_volume_standard',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsyield',
            name='unit_weight',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsyield',
            name='unit_weight_standard',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsresource',
            name='bill_of_materials',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsresource',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsresource',
            name='resource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.resource'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsprocedure',
            name='bill_of_materials',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsprocedure',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsnote',
            name='bill_of_materials',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsnote',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsline',
            name='bill_of_materials',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsline',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsline',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialsline',
            name='unit_standard',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialscharacteristics',
            name='bill_of_materials',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterialscharacteristics',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterials',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterials',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.team'),
        ),
        migrations.AddField(
            model_name='billofmaterialsyield',
            name='bill_of_materials',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterialsyield',
            name='unit_each',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='billofmaterialsyield',
            name='unit_volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='billofmaterialsyield',
            name='unit_volume_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='billofmaterialsyield',
            name='unit_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='billofmaterialsyield',
            name='unit_weight_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='billofmaterialstree',
            name='bill_of_materials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterialstree',
            name='node_bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees_within', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterialstree',
            name='unit_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='billofmaterialsresource',
            name='bill_of_materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requirements', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterialsresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='masterdata.resource'),
        ),
        migrations.AddField(
            model_name='billofmaterialsprocedure',
            name='bill_of_materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterialsnote',
            name='bill_of_materials',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='bill_of_materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='masterdata.item'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='unit_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='masterdata.unitmeasurement'),
        ),
        migrations.AddField(
            model_name='billofmaterialscost',
            name='bill_of_materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterialscharacteristics',
            name='bill_of_materials',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='masterdata.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_of_materials', to='masterdata.team'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
            ],
            options={
                'permissions': [('change_material_deletion_protection', 'Can change deletion protection of material'), ('schedule_permanent_material_deletion', 'Can permanently delete material information')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.item',),
        ),
        migrations.CreateModel(
            name='MaterialCharacteristics',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Material characteristics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.itemcharacteristics',),
        ),
        migrations.CreateModel(
            name='MaterialConversion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.itemconversion',),
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.itemcost',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.item',),
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Product characteristics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.itemcharacteristics',),
        ),
        migrations.CreateModel(
            name='ProductConversion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.itemconversion',),
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.itemcost',),
        ),
        migrations.AddField(
            model_name='historicalbillofmaterials',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.product'),
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterialsprocedure',
            unique_together={('bill_of_materials', 'language')},
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_of_materials', to='masterdata.product'),
        ),
    ]
