# Generated by Django 3.2.1 on 2021-05-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'get_latest_by': ('version',), 'ordering': ['-version', 'state'], 'permissions': [('change_bom_status', 'Can change status of BOM'), ('increment_bom_version', 'Can increment BOM version'), ('submit_bom_for_approval', 'Can submit BOM for approval')], 'verbose_name_plural': 'Bills of materials'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'get_latest_by': ['version'], 'ordering': ['name', 'version']},
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='version_key',
            field=models.CharField(blank=True, editable=False, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='version_key',
            field=models.CharField(blank=True, editable=False, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='version_key',
            field=models.CharField(blank=True, editable=False, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='version_key',
            field=models.CharField(blank=True, editable=False, max_length=26, null=True),
        ),
    ]
