# Generated by Django 3.2.1 on 2021-05-11 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20210507_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsettings',
            name='default_target_product_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter default suggested margin as a proportion of material cost', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_target_product_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter default suggested margin as a proportion of material cost', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
