# Generated by Django 3.2.1 on 2021-05-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20210511_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='production_category',
            field=models.CharField(choices=[('ORDER', 'Make-to-Order'), ('STOCK', 'Make-to-Stock')], default='ORDER', max_length=5, verbose_name='Production Mode'),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='production_category',
            field=models.CharField(choices=[('ORDER', 'Make-to-Order'), ('STOCK', 'Make-to-Stock')], default='ORDER', max_length=5, verbose_name='Production Mode'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='production_category',
            field=models.CharField(choices=[('ORDER', 'Make-to-Order'), ('STOCK', 'Make-to-Stock')], default='ORDER', max_length=5, verbose_name='Production Mode'),
        ),
        migrations.AddField(
            model_name='item',
            name='production_category',
            field=models.CharField(choices=[('ORDER', 'Make-to-Order'), ('STOCK', 'Make-to-Stock')], default='ORDER', max_length=5, verbose_name='Production Mode'),
        ),
    ]
