# Generated by Django 3.2.1 on 2021-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20210511_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='production_category',
        ),
        migrations.RemoveField(
            model_name='historicalmaterial',
            name='production_category',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='production_category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='production_category',
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='production_type',
            field=models.CharField(choices=[('ORDER', 'Make-to-Order'), ('STOCK', 'Make-to-Stock')], default='ORDER', max_length=5, verbose_name='Production Type'),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='production_type',
            field=models.CharField(choices=[('ORDER', 'Make-to-Order'), ('STOCK', 'Make-to-Stock')], default='ORDER', max_length=5, verbose_name='Production Type'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='production_type',
            field=models.CharField(choices=[('ORDER', 'Make-to-Order'), ('STOCK', 'Make-to-Stock')], default='ORDER', max_length=5, verbose_name='Production Type'),
        ),
        migrations.AddField(
            model_name='item',
            name='production_type',
            field=models.CharField(choices=[('ORDER', 'Make-to-Order'), ('STOCK', 'Make-to-Stock')], default='ORDER', max_length=5, verbose_name='Production Type'),
        ),
    ]
