# Generated by Django 3.2.1 on 2021-05-11 20:41

import apps.common.models
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20210511_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'get_latest_by': ('version',), 'ordering': ['-version'], 'verbose_name_plural': 'Bills of materials'},
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicalbillofmaterials',
            name='state',
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.CharField(blank=True, default=apps.common.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('state', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('AWAITING', 'Awaiting Approval'), ('RETURNED', 'Returned for Revisions'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=50, verbose_name='State')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='masterdata.product')),
            ],
            options={
                'verbose_name_plural': 'Product statuses',
                'ordering': ['-version', 'state'],
                'permissions': [('change_product_status', 'Can change status of Product'), ('submit_product_for_approval', 'Can submit Product for approval')],
                'get_latest_by': ('version',),
            },
        ),
    ]
