# Generated by Django 3.2.1 on 2021-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_auto_20210511_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicalmaterial',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='state',
        ),
        migrations.RemoveField(
            model_name='item',
            name='state',
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available?'),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available?'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available?'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available?'),
        ),
    ]
