# Generated by Django 3.2.1 on 2021-05-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20210511_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitemconversion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalitemconversion',
            name='item',
        ),
        migrations.RemoveField(
            model_name='historicalmaterialconversion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmaterialconversion',
            name='item',
        ),
        migrations.RemoveField(
            model_name='historicalproductconversion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproductconversion',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemconversion',
            name='item',
        ),
        migrations.DeleteModel(
            name='MaterialConversion',
        ),
        migrations.DeleteModel(
            name='ProductConversion',
        ),
        migrations.AddField(
            model_name='historicalitemcharacteristics',
            name='allergens_evaluated',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NAN', 'No Evaluation Necessary')], default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalmaterialcharacteristics',
            name='allergens_evaluated',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NAN', 'No Evaluation Necessary')], default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalproductcharacteristics',
            name='allergens_evaluated',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NAN', 'No Evaluation Necessary')], default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='itemcharacteristics',
            name='allergens_evaluated',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NAN', 'No Evaluation Necessary')], default='PENDING', max_length=12),
        ),
        migrations.DeleteModel(
            name='HistoricalItemConversion',
        ),
        migrations.DeleteModel(
            name='HistoricalMaterialConversion',
        ),
        migrations.DeleteModel(
            name='HistoricalProductConversion',
        ),
        migrations.DeleteModel(
            name='ItemConversion',
        ),
    ]
